export const SORT_PRICE_ORDER_ASC="SORT_ORDER_ASC";
export const SORT_PRICE_ORDER_DESC="SORT_ORDER_DESC";

export const SORT_NAME_ORDER_ASC="SORT_NAME_ORDER_ASC";
export const SORT_NAME_ORDER_DESC="SORT_NAME_ORDER_DESC";

export const RESET_FUNCTION="RESET_FUNCTION";

export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FALIURE="GET_PRODUCT_FALIURE";

export const FILTER_FUNCTION="FILTER_FUNCTION";
export const FILTER_FUNCTION_CATEGOERY="FILTER_FUNCTION_CATEGOERY";