export const SORT_PRICE_ORDER_ASC_W="SORT_ORDER_ASC_W";
export const SORT_PRICE_ORDER_DESC_W="SORT_ORDER_DESC_W";

export const SORT_NAME_ORDER_ASC_W="SORT_NAME_ORDER_ASC_W";
export const SORT_NAME_ORDER_DESC_W="SORT_NAME_ORDER_DESC_W";

export const RESET_FUNCTION_W="RESET_FUNCTION_W";

export const GET_PRODUCT_REQUEST_W="GET_PRODUCT_REQUEST_W";
export const GET_PRODUCT_SUCCESS_W="GET_PRODUCT_SUCCESS_W";
export const GET_PRODUCT_FALIURE_W="GET_PRODUCT_FALIURE_W";

export const FILTER_FUNCTION_W="FILTER_FUNCTION_W";
export const FILTER_FUNCTION_CATEGOERY_W="FILTER_FUNCTION_CATEGOERY_W";